<?php
/**
 * RMS Database Installer
 * Automatically creates database tables and sample data
 */

// Database configuration
$db_config = [
    'hostname' => 'localhost',
    'username' => 'root',
    'password' => '',
    'database' => 'rms',
    'charset' => 'utf8mb4'
];

// Create database connection
try {
    $pdo = new PDO(
        "mysql:host={$db_config['hostname']};charset={$db_config['charset']}", 
        $db_config['username'], 
        $db_config['password'],
        [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES {$db_config['charset']}"
        ]
    );
    
    echo "✓ Database connection established\n";
    
} catch (PDOException $e) {
    die("✗ Database connection failed: " . $e->getMessage() . "\n");
}

// Create database if it doesn't exist
try {
    $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$db_config['database']}` DEFAULT CHARACTER SET {$db_config['charset']} COLLATE {$db_config['charset']}_unicode_ci");
    $pdo->exec("USE `{$db_config['database']}`");
    echo "✓ Database '{$db_config['database']}' created/selected\n";
} catch (PDOException $e) {
    die("✗ Failed to create database: " . $e->getMessage() . "\n");
}

// Read and execute SQL schema
$schema_file = dirname(__DIR__) . '/database/rms_schema.sql';

if (!file_exists($schema_file)) {
    die("✗ Schema file not found: $schema_file\n");
}

$sql_content = file_get_contents($schema_file);

// Remove comments and split into individual statements
$sql_content = preg_replace('/--.*$/m', '', $sql_content);
$sql_content = preg_replace('/\/\*.*?\*\//s', '', $sql_content);
$statements = array_filter(array_map('trim', explode(';', $sql_content)));

echo "✓ Schema file loaded, executing " . count($statements) . " statements\n";

// Execute each statement
$executed = 0;
$errors = 0;

foreach ($statements as $statement) {
    if (empty($statement) || strtoupper(substr(trim($statement), 0, 3)) === 'USE') {
        continue;
    }
    
    try {
        $pdo->exec($statement);
        $executed++;
        
        // Show progress for table creation
        if (stripos($statement, 'CREATE TABLE') !== false) {
            preg_match('/CREATE TABLE\s+`?(\w+)`?/i', $statement, $matches);
            if (isset($matches[1])) {
                echo "  ✓ Created table: {$matches[1]}\n";
            }
        }
        
    } catch (PDOException $e) {
        $errors++;
        echo "  ✗ Error executing statement: " . $e->getMessage() . "\n";
        echo "  Statement: " . substr($statement, 0, 100) . "...\n";
    }
}

echo "\n=== Installation Summary ===\n";
echo "Statements executed: $executed\n";
echo "Errors encountered: $errors\n";

// Verify table creation
$tables = $pdo->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);
echo "Tables created: " . count($tables) . "\n";

foreach ($tables as $table) {
    $count = $pdo->query("SELECT COUNT(*) FROM `$table`")->fetchColumn();
    echo "  - $table: $count records\n";
}

if ($errors === 0) {
    echo "\n✓ Database installation completed successfully!\n";
    echo "✓ You can now access the RMS application\n";
} else {
    echo "\n⚠ Database installation completed with $errors errors\n";
    echo "⚠ Please check the error messages above\n";
}

// Create database configuration file
$config_content = "<?php
// Database configuration for RMS
// Auto-generated by installer

\$active_group = 'default';
\$query_builder = TRUE;

\$db['default'] = array(
    'dsn'      => '',
    'hostname' => '{$db_config['hostname']}',
    'username' => '{$db_config['username']}',
    'password' => '{$db_config['password']}',
    'database' => '{$db_config['database']}',
    'dbdriver' => 'mysqli',
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => '{$db_config['charset']}',
    'dbcollat' => '{$db_config['charset']}_unicode_ci',
    'swap_pre' => '',
    'encrypt'  => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE
);
";

$config_file = dirname(__DIR__) . '/application/config/database.php';
file_put_contents($config_file, $config_content);
echo "✓ Database configuration file updated: $config_file\n";

echo "\n=== Next Steps ===\n";
echo "1. Open your web browser\n";
echo "2. Navigate to: http://localhost/rms/\n";
echo "3. The application should now load without database errors\n";
echo "4. Default login credentials will be created in the next update\n";
?>